# https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/controllers/ikea_e2201/ikea_e2201.yaml#L219

# Blueprint Metadata
blueprint:
  name: IKEA E2001/E2002 STYRBAR remote control
  description: |
    # IKEA E2001/E2002 STYRBAR remote control

    Controller automation for executing any kind of action triggered by the provided IKEA E2001/E2002 STYRBAR remote control.
    Allows to optionally loop an action on a button long press.
    Allows for Virtual Double Presses. Needs to be enabled in blueprint.
    Supports Zigbee2MQTT.

  source_url: https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/controllers/ikea_e2201/ikea_e2201.yaml
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  # Device Selector
  input:
    controller_device:
      name: Z2M Controller Device
      description: The controller device to use for the automation. Choose a value only if the remote is integrated with Zigbee2MQTT, ZHA, deCONZ.
      default: ''
      selector:
        # source: https://zigbee.blakadder.com/Ikea_E2201.html
        device:
          filter:
            # source: https://www.zigbee2mqtt.io/devices/E2001_E2002.html#ikea-e2001-e2002
            - integration: mqtt
              manufacturer: IKEA
              model: STYRBAR remote control
            # For backwards compatability with z2m 1.x. model_id is added to end of model rather than a seperate attribute in z2m 2.x
            - integration: mqtt
              manufacturer: IKEA
              model: STYRBAR remote control (E2001/E2002)
          multiple: false
    # inputs for custom actions
    action_button_up_short:
      name: (Optional) Up button short press
      description: Action to run on short up button press.
      default: []
      selector:
        action:
    action_button_up_long:
      name: (Optional) Up button long press
      description: Action to run on long up button press.
      default: []
      selector:
        action:
    action_button_up_release:
      name: (Optional) Up button release
      description: Action to run on up button release after long press.
      default: []
      selector:
        action:
    action_button_up_double:
      name: (Optional) (Virtual) Up button double press
      description: Action to run on double up button press.
      default: []
      selector:
        action:
    action_button_down_short:
      name: (Optional) Down button short press
      description: Action to run on short down button press.
      default: []
      selector:
        action:
    action_button_down_long:
      name: (Optional) Down button long press
      description: Action to run on long down button press.
      default: []
      selector:
        action:
    action_button_down_release:
      name: (Optional) Down button release
      description: Action to run on down button release after long press.
      default: []
      selector:
        action:
    action_button_down_double:
      name: (Optional) (Virtual) Down button double press
      description: Action to run on double down button press.
      default: []
      selector:
        action:
    # inputs for looping custom actions on long button press events until the corresponding release event is received
    long_press_options_section:
      name: Long Press options
      icon: mdi:remote
      collapsed: true
      input:
        button_up_long_max_loop_repeats:
          name: (Optional) Up button long press - Maximum loop repeats
          description: >-
            Maximum number of repeats for the custom action, when looping is enabled.
            Use it as a safety limit to prevent an endless loop in case the corresponding stop event is not received.
          default: 20
          selector:
            number:
              min: 1.0
              max: 1000.0
              mode: slider
              step: 1.0
        button_down_long_max_loop_repeats:
          name: (Optional) Down button long press - Maximum loop repeats
          description: >-
            Maximum number of repeats for the custom action, when looping is enabled.
            Use it as a safety limit to prevent an endless loop in case the corresponding stop event is not received.
          default: 20
          selector:
            number:
              min: 1.0
              max: 1000.0
              mode: slider
              step: 1.0
        helper_long_press_delay:
          name: (Optional) Helper - Long Press delay
          description: Max delay between the pushing and releasing of a button long press event. Increase this value if you notice that the long press action is not triggered properly.
          default: 250
          selector:
            number:
              min: 100.0
              max: 5000.0
              unit_of_measurement: milliseconds
              mode: box
              step: 10.0
    # inputs for enabling double press events
    double_press_options_section:
      name: Double Press options
      icon: mdi:remote
      collapsed: true
      input:
        button_up_double_press_exposed:
          name: (Optional) Expose up button double press event
          description: Choose whether or not to expose the virtual double press event for the up button. Turn this on if you are providing an action for the up button double press event.
          default: false
          selector:
            boolean:
        button_down_double_press_exposed:
          name: (Optional) Expose down button double press event
          description: Choose whether or not to expose the virtual double press event for the down button. Turn this on if you are providing an action for the down button double press event.
          default: false
          selector:
            boolean:
        # helper used to properly adjust the remote button double press events
        helper_double_press_delay:
          name: (Optional) Helper - Double Press delay
          description: Max delay between the first and the second button press for the double press event. Provide a value only if you are using a double press action. Increase this value if you notice that the double press action is not triggered properly.
          default: 250
          selector:
            number:
              min: 100.0
              max: 5000.0
              unit_of_measurement: milliseconds
              mode: box
              step: 10.0
#
# Automation schema
variables:
  # Controller ID
  controller_id: !input controller_device
  # integration id used to select items in the action mapping
  # integration type is set from trigger.id
  integration_id: '{{ trigger.id.split("-")[0] }}'
  # convert input tags to variables, to be used in templates
  # Button Inputs For Loop
  helper_long_press_delay: !input helper_long_press_delay
  button_up_long_max_loop_repeats: !input button_up_long_max_loop_repeats
  button_down_long_max_loop_repeats: !input button_down_long_max_loop_repeats
  # Button Inputs for Virtual Double Press
  helper_double_press_delay: !input helper_double_press_delay
  button_up_double_press_exposed: !input button_up_double_press_exposed
  button_down_double_press_exposed: !input button_down_double_press_exposed
  # mapping between actions and integrations
  actions_mapping:
    z2m:
      # source: https://www.zigbee2mqtt.io/devices/E2201.html#ikea-e2201
      button_up_short: ['on']
      button_up_long: [brightness_move_up]
      button_up_release: [brightness_stop]
      button_down_short: ['off']
      button_down_long: [brightness_move_down]
      button_down_release: [brightness_stop]
      
      button_right_click: [arrow_right_click]
      button_right_hold: [arrow_right_hold]
      button_right_release: [arrow_right_release]
      button_left_click: [arrow_left_click]
      button_left_hold: [arrow_left_hold]
      button_left_release: [arrow_left_release]
      
# Mode Block
mode: single
max_exceeded: silent
#
# Triggers Block
triggers:
  # triggers for zigbee2mqtt
  - trigger: device
    id: z2m-button-up-short
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'on'
  - trigger: device
    id: z2m-button-up-long
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_up
  - trigger: device
    id: z2m-button-up-release
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_stop
  - trigger: device
    id: z2m-button-down-short
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'off'
  - trigger: device
    id: z2m-button-down-long
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_down
  - trigger: device
    id: z2m-button-down-release
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_stop

#
# Conditions Block
conditions:
  - condition: and
    conditions:
      # check that the button event is not empty
      - >-
        {%- set trigger_action -%}
        {%- if integration_id == "z2m" -%}
        {{ trigger.payload }}
        {%- elif integration_id == "zha" -%}
        {{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }}
        {%- elif integration_id == "dcz" -%}
        {{ trigger.event.data.event }}
        {%- endif -%}
        {%- endset -%}
        {{ trigger_action not in ["","None","unknown"] }}
#
# Actions Block
actions:
  #
  # choose the sequence to run based on the received button event
  - choose:
      #
      # Actions for Up Button Single Press / Double Press Virtual
      - conditions:
          - condition: trigger
            id:
              - z2m-button-up-short
        sequence:
          # Check If Double Press is Exposed
          - if:
              - condition: template
                value_template: '{{ button_up_double_press_exposed }}'
            then:
              # Handle Double Press
              - choose:
                  # Wait for z2m/zha/dcz triggers for second Button Press to treat as a Double Press
                  - conditions: []
                    sequence:
                      - wait_for_trigger:
                          # z2m trigger
                          - trigger: device
                            domain: mqtt
                            device_id: !input controller_device
                            type: action
                            subtype: 'on'
                        timeout:
                          milliseconds: '{{ helper_double_press_delay }}'
                        continue_on_timeout: true
                      # If a second button short press is triggered wait.trigger.idx will be defined
                      - if:
                          - condition: template
                            value_template: '{{ wait.trigger.idx is defined }}'
                        # Second short press trigger was received send Hook and Custom Actions as a Double Press
                        then:
                          - choose:
                              - conditions: []
                                sequence: !input action_button_up_double
                        # Second short press trigger was not received send Hook and Custom Actions as a Single Press
                        else:
                          - choose:
                              - conditions: []
                                sequence: !input action_button_up_short
            # Double Press is Not Exposed So send Hook and Custom Actions as a Single Press
            else:
              - choose:
                  - conditions: []
                    sequence: !input action_button_up_short
      #
      # Actions for Down Button Single Press / Double Press Virtual
      - conditions:
          - condition: trigger
            id:
              - z2m-button-down-short
        sequence:
          # Check If Double Press is Exposed
          - if:
              - condition: template
                value_template: '{{ button_down_double_press_exposed }}'
            # Handle Double Press
            then:
              - choose:
                  # Wait for z2m/zha/dcz triggers for second Button Press to treat as a Double Press
                  - conditions: []
                    sequence:
                      - wait_for_trigger:
                          # z2m trigger
                          - trigger: device
                            domain: mqtt
                            device_id: !input controller_device
                            type: action
                            subtype: 'off'
                        timeout:
                          milliseconds: '{{ helper_double_press_delay }}'
                        continue_on_timeout: true
                      # If a second button short press is triggered wait.trigger.idx will be defined
                      - if:
                          - condition: template
                            value_template: '{{ wait.trigger.idx is defined }}'
                        # Second short press trigger was received send Hook and Custom Actions as a Double Press
                        then:
                          # run the custom action
                          - choose:
                              - conditions: []
                                sequence: !input action_button_down_double
                        # Second short press trigger was not received send Hook and Custom Actions as a Single Press
                        else:
                          # run the custom action
                          - choose:
                              - conditions: []
                                sequence: !input action_button_down_short
            # Double Press is Not Exposed So send Hook and Custom Actions as a Single Press
            else:
              # run the custom action
              - choose:
                  - conditions: []
                    sequence: !input action_button_down_short
      #
      # Actions for Button Up Long Press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-up-long
        sequence:
          # Repeat the Long Press Actions for the set number of loops
          - repeat:
              count: !input button_up_long_max_loop_repeats
              sequence:
                - parallel:
                    - sequence:
                        - choose:
                            - conditions: []
                              sequence: !input action_button_up_long
                    - sequence:
                        - choose:
                            # Wait for z2m/zha/dcz triggers for Button Long Press Release to stop looping
                            - conditions: []
                              sequence:
                                - wait_for_trigger:
                                    - trigger: device
                                      domain: mqtt
                                      device_id: !input controller_device
                                      type: action
                                      subtype: brightness_stop
                                  timeout:
                                    milliseconds: !input helper_long_press_delay
                                  continue_on_timeout: true
                                # If a Button Long Release is triggered wait.trigger.idx will be defined stop the loop before long_max_loop_repeats
                                - if:
                                    - condition: template
                                      value_template: '{{ wait.trigger.idx is defined }}'
                                  then:
                                    # run the custom action
                                    - choose:
                                        - conditions: []
                                          sequence: !input action_button_up_release
                                    # Stop the repeat loop
                                    - stop: button_up_released
      #
      # Actions for Button Down Long Press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-down-long
        sequence:
          # Repeat the Long Press Actions for the set number of loops
          - repeat:
              count: !input button_down_long_max_loop_repeats
              sequence:
                - parallel:
                    - sequence:
                        - choose:
                            - conditions: []
                              sequence: !input action_button_down_long
                    - sequence:
                        - choose:
                            # Wait for z2m/zha/dcz triggers for Button Long Press Release to stop looping
                            - conditions: []
                              sequence:
                                - wait_for_trigger:
                                    - trigger: device
                                      domain: mqtt
                                      device_id: !input controller_device
                                      type: action
                                      subtype: brightness_stop
                                  timeout:
                                    milliseconds: !input helper_long_press_delay
                                  continue_on_timeout: true
                                # If a Button Long Release is triggered wait.trigger.idx will be defined stop the loop before long_max_loop_repeats
                                - if:
                                    - condition: template
                                      value_template: '{{ wait.trigger.idx is defined }}'
                                  then:
                                    # run the custom action
                                    - choose:
                                        - conditions: []
                                          sequence: !input action_button_down_release
                                    # Stop the repeat loop
                                    - stop: button_down_released
      #
      # Actions for Up Button long press released
      - conditions:
          - condition: trigger
            id:
              - z2m-button-up-release
        sequence:
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_up_release
      #
      # Actions for Down Button long press released
      - conditions:
          - condition: trigger
            id:
              - z2m-button-down-release
        sequence:
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_down_release
